version: '3.1'

services:
  postgres_db:
    container_name: alfred_database_server
    image: postgres
    shm_size: 1g
    restart: always
    command: postgres -c 'max_connections=1000'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aflred@server
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
